### ISSUE TITLE
Codec not displaying complete list of codecs

### ISSUE THREAD

**Issue by ishtiaq156** [tyirvine/Informant#13]
Here's one example

![Screen Shot 2021-09-01 at 12 08 41 AM](https://user-images.githubusercontent.com/25985759/131610639-5e1a108a-5139-47cb-8396-fb0afc34ea59.png)

It would be nice if it shows the list of all codecs like how "Path" does into multiple lines or show the list when the mouse is hovered over.

Version: 0.08.6

Great app btw.

**Comment by tyirvine** [comment]
Good find! I guess I was always testing on videos/movies with one or two codecs lol. I'll remove it's one line limit!

**Comment by tyirvine** [comment]
Fixed in 0.08.7!  🎉
