### ISSUE TITLE
Arrow key Navigation

### ISSUE THREAD

**Issue by legendaryaman** [tyirvine/Informant#14]
**Describe the bug**
Informant does not **update** the info when navigating files and folders with **arrow keys.**

**How or when does this happen?**
Everywhere.

**Informant version**

0.08.6

**Comment by tyirvine** [comment]
@legendaryaman Have you tried closing the app and reopening it? There's an issue where sometimes Accessibility permissions don't kick in until the app is restarted.

After that arrow key navigation should work ok

**Comment by legendaryaman** [comment]
Fixed. It is an Accessibility issue. Thanks.

**Comment by tyirvine** [comment]
> Fixed. It is an Accessibility issue. Thanks.

@legendaryaman Yeah that sucks, I've run into that a few times. I think in the setup process I'll just add a button and instructions to quit and reopen the app.

**Comment by ishtiaq156** [comment]
@tyirvine a suggestion - pop-up saying to force quit and restart the app once Accessibility permissions are granted.
I see many other apps like screen recorders and screen-sharing doing this

**Comment by tyirvine** [comment]
Fixed in 0.08.7!  🎉

The user is now forced to close the app and reopen it with accessibility enabled now
