### ISSUE TITLE
Bitrate information for mp3 files AND compatible with Path Finder app?

### ISSUE THREAD

**Issue by wilky761** [tyirvine/Informant#16]
So far, I'm impressed with this app.

I have two requests please:

1) I use Path Finder (made by Cocoatech) as a replacement to Finder as it has much more features such as dual-pane view etc. etc. I noticed that Informant works with Finder but it does not work with Path Finder. Would it be possible to make Informant work when using Path Finder?

2) There aren't many apps where I can see the Bitrate of my mp3 files. Is this something you could add to Informant, so that when you click on one mp3 file, it shows what bitrate it is? i.e. 192, 256, 320kbps

Thanks

**Comment by tyirvine** [comment]
1. Unfortunately Informant relies on communication with Finder via Apple Scripts in order to work.

I'll see if there's another way to accomplish this.

2. Yes a few people have requested bitrate lol. I'll add it for both video and audio! I'll update this issue when it's added in.

**Comment by wilky761** [comment]
Amazing, thank you very much. Appreciated :)

**Comment by tyirvine** [comment]
Video and audio bitrate has been added in version 0.08.8! 🎉
