### ISSUE TITLE
German Localisation Issues

### ISSUE THREAD

**Issue by ephemeraleternity** [tyirvine/Informant#3]
The German localisation of the App has some issues. I've corrected them where I could and attached an improved version of the Localizable.strings below. Please take note of the comments included in the file.

An issue which still persists is "Informationen In Menüleiste Anzeigen" & "Informationen In Menüleiste Ausblenden" being capitalised when right clicking on the Informant menubar Icon. It should be "Informationen in Menüleiste anzeigen" & "Informationen in Menüleiste ausblenden".

[German_Localizable.strings.zip](https://github.com/tyirvine/Informant/files/7032074/German_Localizable.strings.zip)

**Comment by tyirvine** [comment]
Okay, noted. I have an auto-capitalization function linked to that I believe so I'll be sure to remove it and simply capitalize the English string and then update translations. As well as merge your changes in.

**Comment by tyirvine** [comment]
Fixed in 0.08.6 🎉

<img width="287" alt="Screen Shot 2021-08-30 at 11 14 11 PM" src="https://user-images.githubusercontent.com/39813066/131446786-d07671ad-ed0a-43be-b1e9-7f7b64eac3b3.png">
