### ISSUE TITLE
How to open preferences

### ISSUE THREAD

**Issue by Auratelience** [tyirvine/Informant#7]
Hi. Probably an easy question. I've been using Informant for ages but just downloaded the new version with the floating bar which I like. My question is how to show the preferences pane as I cant seem to open it.

Thanks, Auratelience

**Comment by tyirvine** [comment]
You should be able to open it by clicking the icon in the menubar, and then clicking the `Preferences...` menu item. I just tried it on Sonoma 14.1 and it seems to have worked. If that doesn't work you can also try opening up Spotlight with <kbd>⌘</kbd><kbd>Space</kbd> and then searching for Informant and hitting enter. That should also open up the preferences pane.

If neither of these approaches work then there may be an issue with the program. I haven't done an update in a long time so I apologize for that! I'm going to try and reincorporate the classic view into the new version.

**Comment by Auratelience** [comment]
Yes it seems to work some of the time. The main issue is I disabled the menubar icon.
